# -*- coding: utf-8 -*-
"""
임베딩 매칭용 필드 설명 텍스트.
- aaa1/lsd: 원본 프롬프트의 Meaning/Definition 문장을 그대로 가져옴 (매칭 정확도를 위해 설명문 사용)
- motional: 별도 Meaning이 없어서 우선 필드명을 사람이 읽을 수 있게 풀어쓴 문장으로 대체.
  (나중에 실제 Motional 정의 문서 있으면 그걸로 교체 필요 — 지금은 필드명 기반 approximation)
"""

FIELD_DESCRIPTIONS = {
    # ---------- aaa1_tags (ODD static) ----------
    "contaminated_lane": "진흙, 기름, 잔해물, 흙, 웅덩이 등으로 오염되어 차선 인식이 어려운 도로",
    "invisible_lanes_city_3_5_lanes_many_vehicles_ahead": "도시의 3~5차선 도로에서 앞에 차량이 많아 차선이 보이지 않는 상황",
    "no_lane_mark_road": "차선 표시가 전혀 없는 도로",
    "two_three_wheelers_carrying_loads": "짐을 싣고 있는 이륜차 또는 삼륜차",
    "vehicles_carrying_loads_or_protruding_cargo": "짐을 싣거나 화물이 튀어나온 차량",
    "bullock_carts": "소가 끄는 달구지, 소달구지",
    "hand_pulled_carts": "사람이 손으로 끄는 수레",
    "animal_sitting_or_standing_cow": "앉아있거나 서있는 소",
    "animal_large_dog": "큰 개",
    "barricades": "도로 공사장이나 통제 구역의 바리케이드",
    "crowded_pedestrian": "보행자가 밀집되어 있는 장면",
    "yellow_line_near_curb": "연석 근처의 노란색 차선",
    "yellow_line_low_sun": "역광(낮은 태양) 상황에서의 노란색 차선",
    "white_line_low_sun": "역광(낮은 태양) 상황에서의 흰색 차선",
    "road_boundary_low_sun": "역광(낮은 태양) 상황에서의 도로 경계",
    "road_boundary_guardrail_or_wall": "가드레일이나 벽으로 이루어진 도로 경계",
    "road_boundary_lane_separator": "차선 분리대로 이루어진 도로 경계",
    "road_boundary_flat": "평평한 갓길로 이루어진 도로 경계 (턱이나 장벽 없음)",
    "road_boundary_parked_car": "주차된 차량들이 도로 경계를 형성하는 상황",

    # ---------- aaa1_context ----------
    "time:day": "낮 시간대, 주간, 밝은 자연광",
    "time:dawn_evening": "새벽, 황혼, 노을, 해질녘, 여명, 일출/일몰 시간대",
    "time:night": "야간, 밤 시간대, 어두운 상황, 인공조명 의존",
    "da_road_type:public_road_highway": "고속도로, 자동차 전용도로",
    "da_road_type:public_road_city": "도심 도로, 시내 도로",
    "da_road_type:public_road_rural": "시골길, 국도, 저밀도 지방 도로",
    "da_road_type:parking_lot_outdoor": "실외 주차장",
    "da_road_type:parking_lot_indoor": "실내 주차장, 지하 주차장",
    "weather:clear": "맑은 날씨",
    "weather:rainy": "비가 오는 날씨, 우천",
    "weather:heavy_rainy": "폭우, 강한 비",
    "weather:snow": "눈, 강설",
    "weather:fog": "안개, 짙은 안개",

    # ---------- lsd_tags (night light-source) ----------
    "low_streetlight_road": "가로등이 적은 어두운 야간 도로",
    "oncoming_vehicle_far_60m": "멀리서(약 60m 이상) 마주 오는 차량의 헤드램프",
    "oncoming_vehicle_taillight_cluster": "마주 오는 차량 헤드램프와 앞선 차량 테일램프가 겹쳐 보이는 상황",
    "motorbike_headlamp": "오토바이의 단일 헤드램프 광원",
    "reflector_guardrail": "가드레일에 반사되는 헤드램프 반사광",
    "reflector_lane_divider": "차선 분리봉(델리네이터)에 반사되는 광원",
    "reflector_tunnel_lowmid_light": "터널 내부 중하단부의 조명 및 반사광",
    "reflector_white_all": "흰색/밝은 반사판이나 표지판의 반사광",
    "sign_strong_light_reflection": "도로 표지판에 강하게 반사되는 전조등 빛",
    "sign_white_heavy_reflection": "흰색 표지판의 강한 반사광",
    "camera_torn_frame": "카메라 센서 오류로 찢어지거나 깨진 프레임 (이미지 손상)",

    # ---------- motional_tags (공식 정의) ----------
    "behind_pedestrian_on_driveable": "Ego 차량이 주행 가능 영역 내에 위치한 보행자의 후방에 존재한다",
    "near_barrier_on_driveable": "Ego 차량이 주행 가능 영역 내부 또는 그에 인접한 장벽 및 경계 구조물 부근에 위치한다",
    "waiting_for_pedestrian_to_cross": "Ego 차량은 보행자가 횡단 중이거나 횡단을 시도할 때 느린 주행 또는 정지 상태로 대기한다",
    "starting_straight_traffic_light_intersection_traversal": "Ego 차량이 신호등이 설치된 교차로에서 직진 주행을 개시한다",
    "starting_u_turn": "Ego 차량이 유턴을 개시하여 주행 방향을 반전시킨다",
    "traversing_intersection": "Ego 차량이 교차로를 통과하는 중이다",
    "traversing_traffic_light_intersection": "Ego 차량이 신호등이 설치된 교차로를 통과하는 중이다",
    "on_carpark": "Ego 차량이 주차장 또는 주차 구역 내에 위치한다",
    "on_intersection": "Ego 차량이 현재 교차로 내부 또는 그 직전 인접 구역에 위치한다",
    "on_traffic_light_intersection": "Ego 차량이 신호등에 의해 제어되는 교차로에 진입해 있거나 그 내부에 위치한다",
    "accelerating_at_traffic_light": "Ego 차량이 신호등 통제 구역 또는 그 인근에서 가속한다",
    "stationary_in_traffic": "Ego 차량이 주변 교통량 또는 정체 구간으로 인해 정지 상태이거나 이에 준하는 상태를 유지한다",
    "crossed_by_bike": "자전거 또는 자전거 탑승자가 Ego 차량의 예상 주행 경로를 횡단한다",
    "crossed_by_vehicle": "타 차량이 Ego 차량의 진행 방향을 횡단한다",
    "crossed_by_motorcycle": "이륜차 또는 이륜차 탑승자가 Ego 차량의 예상 주행 경로를 횡단한다",
    "on_stopline_traffic_light": "Ego 차량이 신호등에 의해 통제되는 정지선에 위치한다",
    "near_multiple_bikes": "Ego 차량이 다수의 자전거 또는 자전거 탑승자 인근에 위치한다",
    "near_multiple_vehicles": "Ego 차량이 다수의 타 차량 인근에 위치한다",
    "near_multiple_motorcycle": "Ego 차량이 다수의 이륜차 또는 이륜차 탑승자 인근에 위치한다",
    "accelerating_at_crosswalk": "Ego 차량이 횡단보도 또는 그 인근에서 가속한다",
    "stationary_at_crosswalk": "Ego 차량이 횡단보도 또는 그 인근에서 정지 상태이거나 이에 준하는 상태를 유지한다",
    "stopping_at_crosswalk": "Ego 차량이 감속하여 횡단보도 또는 그 인근에서 정지한다",
    "high_lateral_acceleration": "Ego 차량이 급선회, 곡선 구간 주행 또는 회피 기동 중 높은 횡가속도를 겪는다",
    "near_high_speed_vehicle": "Ego 차량이 고속 주행 차량 또는 상대 속도가 높은 타 차량의 인근에 위치한다",
    "near_long_vehicle": "Ego 차량이 트럭, 버스 등 대형 차량의 인근에 위치한다",
    "near_multiple_pedestrians": "Ego 차량이 다수의 보행자 인근에 위치한다",
    "near_pedestrian_on_crosswalk": "Ego 차량이 횡단보도를 횡단 중인 보행자 인근에 위치한다",
    "near_pedestrian_on_crosswalk_with_ego": "Ego 차량과 보행자가 동일한 횡단보도 부근 또는 그 위에 공존한다",
    "starting_high_speed_turn": "Ego 차량이 비교적 고속을 유지하며 조향(방향 전환)을 개시한다",
    "starting_low_speed_turn": "Ego 차량이 비교적 저속을 유지하며 조향(방향 전환)을 개시한다",
    "traversing_crosswalk": "Ego 차량이 횡단보도를 통과하는 중이다",
    "on_stopline_crosswalk": "Ego 차량이 횡단보도와 연계된 정지선에 위치한다",
    "high_magnitude_jerk": "Ego 차량이 급격한 가속 또는 감속을 겪으며, 이는 유의미한 저크(Jerk) 변화를 수반한다",
    "stationary": "Ego 차량이 정지 상태이거나 이에 준하는 상태를 유지한다",
    "high_magnitude_speed": "Ego 차량이 해당 시나리오의 예상 속도 범위 대비 현저히 높은 속도로 주행한다",
    "low_magnitude_speed": "Ego 차량이 저속으로 주행 중이나 완전한 정지 상태는 아니다",
    "medium_magnitude_speed": "Ego 차량이 정상 또는 중간 수준의 속도 범위 내에서 주행한다",
    "starting_left_turn": "Ego 차량이 좌회전 기동을 개시한다",
    "starting_right_turn": "Ego 차량이 우회전 기동을 개시한다",
    "changing_lane": "Ego 차량이 현재 차로에서 타 차로로 차선 변경을 수행 중이다",
    "changing_lane_to_left": "Ego 차량이 현재 차로에서 좌측 차로로 차선 변경을 수행 중이다",
    "changing_lane_to_right": "Ego 차량이 현재 차로에서 우측 차로로 차선 변경을 수행 중이다",
    "accelerating_at_traffic_light_with_lead": "Ego 차량이 선행 차량이 존재하는 상태에서 신호등 전방 또는 인근에서 가속한다",
    "accelerating_at_traffic_light_without_lead": "Ego 차량이 선행 차량이 부재한 상태에서 신호등 전방 또는 인근에서 가속한다",
    "following_lane_with_lead": "Ego 차량이 선행 차량이 존재하는 상태에서 현재 차로를 유지하며 주행한다",
    "following_lane_with_slow_lead": "Ego 차량이 저속으로 주행하는 선행 차량의 후방에서 차로를 유지하며 주행한다",
    "following_lane_without_lead": "Ego 차량이 선행 차량이 부재한 상태에서 현재 차로를 유지하며 주행한다",
    "stationary_at_traffic_light_with_lead": "Ego 차량이 선행 차량이 존재하는 상태에서 신호등에 의해 정지 상태이거나 이에 준하는 상태를 유지한다",
    "stationary_at_traffic_light_without_lead": "Ego 차량이 선행 차량이 부재한 상태에서 신호등에 의해 정지 상태이거나 이에 준하는 상태를 유지한다",
    "stopping_at_traffic_light_with_lead": "Ego 차량이 선행 차량이 존재하는 상태에서 신호등 전방에서 감속 및 정지한다",
    "stopping_at_traffic_light_without_lead": "Ego 차량이 선행 차량이 부재한 상태에서 신호등 전방에서 감속 및 정지한다",
    "stopping_with_lead": "Ego 차량이 선행 차량을 추종하며 감속 및 정지한다",
    "stopping_without_lead": "Ego 차량이 선행 차량이 부재한 상태에서 감속 및 정지한다",
    "behind_bike": "Ego 차량이 자전거 또는 자전거 탑승자의 후방에서 동일하거나 연관된 경로를 따라 주행한다",
    "behind_long_vehicle": "Ego 차량이 트럭, 버스 등 대형 차량의 후방에서 주행한다",
    "behind_motorcycle": "Ego 차량이 이륜차 또는 이륜차 탑승자의 후방에서 동일하거나 연관된 경로를 따라 주행한다",
    "changing_lane_with_lead": "Ego 차량이 선행 차량이 존재하는 차로에서 차선 변경을 수행 중이다",
    "changing_lane_with_trail": "Ego 차량이 후방에 추종 차량이 존재하는 상태에서 차선 변경을 수행 중이다",
}